### ISSUE TITLE
ValueError: Not a boolean:

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#30]
I am using it with py3 virtualenv (python3 -m venv env ) on Debian Testing 

python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/media/DRIVE/opt/ytsm/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line                                                  
    utility.execute()
  File "/media/DRIVE/opt/ytsm/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute                                                                    
    settings.INSTALLED_APPS
  File "/media/DRIVE/opt/ytsm/env/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__                                                                            
    self._setup(name)
  File "/media/DRIVE/opt/ytsm/env/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup                                                                                 
    self._wrapped = Settings(settings_module)
  File "/media/DRIVE/opt/ytsm/env/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__                                                                              
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/DRIVE/opt/ytsm/app/YtManager/settings.py", line 226, in <module>
    load_config_ini()
  File "/media/DRIVE/opt/ytsm/app/YtManager/settings.py", line 177, in load_config_ini
    DEBUG = cfg.getboolean('global', 'Debug', fallback=_DEFAULT_DEBUG)
  File "/usr/lib/python3.6/configparser.py", line 829, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 809, in _get_conv
    **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.6/configparser.py", line 1155, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean:

```
pip3 install --no-cache-dir -r requirements.txt
```

```Requirement already satisfied: apscheduler in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: gunicorn in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: django in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: django-crispy-forms in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: dj_database_url in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: youtube-dl in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: google-api-python-client in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: google_auth_oauthlib in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: oauth2client in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: psycopg2-binary in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: python-dateutil in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: pytz in ./env/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
Requirement already satisfied: setuptools>=0.7 in ./env/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
Requirement already satisfied: tzlocal>=1.2 in ./env/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
Requirement already satisfied: six>=1.4.0 in ./env/lib/python3.6/site-packages (from apscheduler->-r requirements.txt (line 1))
Requirement already satisfied: google-auth-httplib2>=0.0.3 in ./env/lib/python3.6/site-packages (from google-api-python-client->-r requirements.txt (line 7))
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in ./env/lib/python3.6/site-packages (from google-api-python-client->-r requirements.txt (line 7))
Requirement already satisfied: httplib2<1dev,>=0.9.2 in ./env/lib/python3.6/site-packages (from google-api-python-client->-r requirements.txt (line 7))
Requirement already satisfied: google-auth>=1.4.1 in ./env/lib/python3.6/site-packages (from google-api-python-client->-r requirements.txt (line 7))
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./env/lib/python3.6/site-packages (from google_auth_oauthlib->-r requirements.txt (line 8))
Requirement already satisfied: pyasn1>=0.1.7 in ./env/lib/python3.6/site-packages (from oauth2client->-r requirements.txt (line 9))
Requirement already satisfied: rsa>=3.1.4 in ./env/lib/python3.6/site-packages (from oauth2client->-r requirements.txt (line 9))
Requirement already satisfied: pyasn1-modules>=0.0.5 in ./env/lib/python3.6/site-packages (from oauth2client->-r requirements.txt (line 9))
Requirement already satisfied: cachetools>=2.0.0 in ./env/lib/python3.6/site-packages (from google-auth>=1.4.1->google-api-python-client->-r requirements.txt (line 7))
Requirement already satisfied: requests>=2.0.0 in ./env/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google_auth_oauthlib->-r requirements.txt (line 8))
Requirement already satisfied: oauthlib>=0.6.2 in ./env/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google_auth_oauthlib->-r requirements.txt (line 8))
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./env/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib->-r requirements.txt (line 8))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib->-r requirements.txt (line 8))
Requirement already satisfied: idna<2.8,>=2.5 in ./env/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib->-r requirements.txt (line 8))
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib->-r requirements.txt (line 8))
```

**Comment by chibicitiberiu** [comment]
That environment variable is used in the dockerfile. We can comment it as a temp fix.

I think the right way to fix this issue would be to allow the application to start even if there are configuration errors, and show a 'warnings' banner (I described this [in this comment](https://github.com/chibicitiberiu/ytsm/pull/27#issuecomment-435823283)).

**Comment by dannyhanes** [comment]
I am following the installation instructions on the main page and ran into a similar issue. I have installed all of the requirements. 

Ubuntu 16.04.5 LTS

```
cd /opt/ytsm/app

python3 manage.py migrate

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/ytsm/app/YtManager/settings.py", line 226, in <module>
    load_config_ini()
  File "/opt/ytsm/app/YtManager/settings.py", line 177, in load_config_ini
    DEBUG = cfg.getboolean('global', 'Debug', fallback=_DEFAULT_DEBUG)
  File "/usr/lib/python3.5/configparser.py", line 826, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 1152, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean:
```

I then tried commenting out line 7 of the config.ini and this was the result. 

```
python3 manage.py migrate

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/ytsm/app/YtManagerApp/models.py", line 180
    return f'folder {self.id}, name="{self.name}"'
                                                 ^
SyntaxError: invalid syntax
```

**Comment by rytilahti** [comment]
@dannyhanes to the second error, f-strings (as seen in the traceback) are first available since python 3.6.

**Comment by dannyhanes** [comment]
@rytilahti As someone who has just been following the instructions (copy paste) and has no idea what thats means.....what do I do? lol

**Comment by chibicitiberiu** [comment]
Make sure you are running at least Python 3.6.

**Comment by chibicitiberiu** [comment]
Closing as fixed
