### ISSUE TITLE
error while downloading added playlist

### ISSUE THREAD

**Issue by saveyour** [chibicitiberiu/ytsm#61]
i'm using a fresh install of the latest version (git clone'd it yesterday). after adding a playlist to download i eventually encounter this error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/ytsm/app/YtManagerApp/management/jobs/synchronize.py", line 114, in synchronize
    __check_new_videos_sub(subscription, yt_api)
  File "/home/ubuntu/ytsm/app/YtManagerApp/management/jobs/synchronize.py", line 21, in __check_new_videos_sub
    for item in yt_api.playlist_items(subscription.playlist_id):
  File "/home/ubuntu/ytsm/app/external/pytaw/pytaw/youtube.py", line 494, in __next__
    return create_resource_from_api_response(self.youtube, item)
  File "/home/ubuntu/ytsm/app/external/pytaw/pytaw/youtube.py", line 651, in create_resource_from_api_response
    return PlaylistItem(youtube, id, item)
  File "/home/ubuntu/ytsm/app/external/pytaw/pytaw/youtube.py", line 719, in __init__
    self._update_attributes()
  File "/home/ubuntu/ytsm/app/external/pytaw/pytaw/youtube.py", line 799, in _update_attributes
    for key, val in raw_value.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by enemyjay** [comment]
I have this same issue, but have found that it doesnt effect all playlists. 
https://www.youtube.com/playlist?list=PLAzrgbu8gEMIIK3r4Se1dOZWSZzUSadfZ (Hot Ones) fails on me, same errors as @saveyour 
https://www.youtube.com/playlist?list=PL59B9338E1B079557 (We Are Scientists) works without issue

Just wanted to add that in case it turns out to be relevant.
