### ISSUE TITLE
Downloading videos does not work - : "token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#83]
I am using the virtualenv method. Everything works except when I try to download a video, I see this in the logs.

```
   ret = yt.download(["https://www.youtube.com/watch?v=" + self.__video.video_id])                                                                                                 [10/45301]
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2002, in download                                                                                 
    return                                                                                                                                                                                    
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 816, in extract_info                                                                              
    self.report_error(msg)                                                                                                                                                                    
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 621, in report_error                                                                              
    else:                                                                                                                                                                                     
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 591, in trouble                                                                                   
    exc_info = sys.exc_info()[1].exc_info                                                                                                                                                     
youtube_dl.utils.DownloadError: ERROR: QSjx8o5ZrOQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                            
    
2019-10-06 19:40:59,376 | DownloadVideoJob | scheduler.py:249 | CRITICAL | Job failed with exception: Traceback (most recent call last):
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    'and will probably not work.')
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    country = self._downloader.params.get('geo_bypass_country', None)
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1674, in _real_extract
youtube_dl.utils.ExtractorError: QSjx8o5ZrOQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    
During handling of the above exception, another exception occurred:
    
Traceback (most recent call last):
  File "/media/SYSLINX/opt/ytsm/app/YtManagerApp/scheduler.py", line 245, in _run_job
    job_instance.run()
  File "/media/SYSLINX/opt/ytsm/app/YtManagerApp/management/jobs/download_video.py", line 40, in run
    ret = yt.download(["https://www.youtube.com/watch?v=" + self.__video.video_id])
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2002, in download
    return
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 816, in extract_info
    self.report_error(msg)
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 621, in report_error
    else:
  File "/media/VIDEO/ytsm/.env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 591, in trouble
    exc_info = sys.exc_info()[1].exc_info
youtube_dl.utils.DownloadError: ERROR: QSjx8o5ZrOQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

INFO:apscheduler.executors.default:Job "YtsmScheduler._run_job (trigger: date[2019-10-06 19:40:56 UTC], next run at: 2019-10-06 19:40:56 UTC)" executed successfully
2019-10-06 19:40:59,403 | apscheduler.executors.default | base.py:144 | INFO | Job "YtsmScheduler._run_job (trigger: date[2019-10-06 19:40:56 UTC], next run at: 2019-10-06 19:40:56 UTC)" exe
cuted successfully



```

**Comment by cyberjacob** [comment]
As the error message suggests, this is an issue you youtube-dl, and needs to be reported to their bug tracker at https://yt-dl.org/bug
